#server:
#  port: 80
#spring:
#  application:
#    name: springboot_demo1
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  data:
#    redis:
#      database: 0
#      host: 127.0.0.1
#      port: 6379
#      password:
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    # 如果使用 MyBatis
#    org.mybatis: DEBUG
#    com.你的mapper包路径: DEBUG
#
#
#
#
